//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SSUDemo.rc
//
#define IDD_SSUDEMO_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_PAGE_ACCESS                 129
#define IDD_PAGE_CONFIG                 130
#define IDD_PAGE_INVENTORY              131
#define IDD_PAGE_CONFIG_PRIV            132
#define IDD_DLG_PORTSET                 133
#define IDD_PAGE_NODE_EXPLORE           134
#define IDD_DIALOG_MSG_OKCANCEL         135
#define IDD_DIALOG_MSG_OK               136
#define IDD_PAGE_NETADDR_TCPIP          138
#define IDD_PANE_NODE_TCPIP             139
#define IDD_PAGE_ACCESS_EX              140
#define IDD_PANE_NODE_RS485             141
#define IDD_PAGE_NETADDR_RS485          142
#define IDC_TAB_PAGES                   1000
#define IDC_BTN_CONNECT                 1002
#define IDC_BTN_TAGQUERY                1002
#define IDC_COMBO_SECT_READ             1003
#define IDC_BTN_CONFIG_END              1003
#define IDC_BTN_DISCONNECT              1003
#define IDC_BTN_TAG_READ                1004
#define IDC_BTN_CONFIG_GET              1004
#define IDC_BTN_TAG_WRITE               1005
#define IDC_BTN_CONFIG_BEGIN            1005
#define IDC_BTN_CONFIG_SET              1005
#define IDC_COMBO_SECT_WRITE            1006
#define IDC_EDIT_CONN_PWD               1006
#define IDC_COMBO_SECT_LOCK             1007
#define IDC_COMBO_BEEP_ENABLE           1007
#define IDC_COMBO_OPT_LOCK              1008
#define IDC_EDIT_RFCENTER               1008
#define IDC_COMBO_SECT_LOCK2            1009
#define IDC_EDIT_RFDeviation            1009
#define IDC_EDIT_EPC                    1010
#define IDC_EDIT_RFSTEP                 1010
#define IDC_EDIT_RFGAIN                 1011
#define IDC_BTN_CONNPWD_SET             1011
#define IDC_EDIT_ACCPWD                 1011
#define IDC_CHECK_ANT0                  1012
#define IDC_EDIT_WRITE_PWD_ACCESS       1012
#define IDC_EDIT_INVT_BUFTM             1013
#define IDC_BTN_NETADDR_SET             1013
#define IDC_EDIT_WRITE_EPC              1013
#define IDC_CHECK_ANT1                  1014
#define IDC_EDIT_WRITE_PWD_KILL         1014
#define IDC_EDIT_START_READ             1015
#define IDC_CHECK_ANT2                  1015
#define IDC_EDIT_WORDS_READ             1016
#define IDC_CHECK_ANT3                  1016
#define IDC_EDIT_DATA_READ              1017
#define IDC_BTN_NETADDR_GET             1017
#define IDC_EDIT_START_READ_USR         1017
#define IDC_EDIT_START_WRITE            1018
#define IDC_COMBO_IVNT_AUTO             1018
#define IDC_BTN_INVT_START              1018
#define IDC_EDIT_INVT_IDLEMIN           1018
#define IDC_EDIT_WORDS_WRITE            1019
#define IDC_COMBO_INVT_SESS             1019
#define IDC_LIST_TAGS                   1019
#define IDC_EDIT_DATA_WRITE             1020
#define IDC_EDIT_INVT_QMAX              1020
#define IDC_EDIT_INVT_IDLEFRACT         1020
#define IDC_EDIT_PWD_WRITE              1021
#define IDC_EDIT_INVT_QMIN              1021
#define IDC_CHECK_INVT_AUTO             1021
#define IDC_EDIT_START_WRITE_USR        1021
#define IDC_EDIT_PWD_LOCK               1022
#define IDC_EDIT_INVT_QMINTRIES         1022
#define IDC_CHECK_INVT_REPORT           1022
#define IDC_EDIT_PWD_LOCK2              1023
#define IDC_EDIT_Q                      1023
#define IDC_EDIT_MSG                    1023
#define IDC_EDIT_PWD_ACC                1023
#define IDC_COMBO_RF_GAIN               1023
#define IDC_BTN_TAG_LOCK                1024
#define IDC_EDIT_TAGCOUNT               1024
#define IDC_BTN_PRIVCONF_GET            1024
#define IDC_BTN_TAG_KILL                1025
#define IDC_BTN_TIMING_SET              1025
#define IDC_EDIT_INTERVAL               1025
#define IDC_COMBO_INVT_QMAX             1025
#define IDC_EDIT_PWD_LOCK3              1026
#define IDC_EDIT_NODEADDR               1026
#define IDC_EDIT_PWD_KILL               1026
#define IDC_COMBO_INVT_QMIN             1026
#define IDC_EDIT_COMPORT                1027
#define IDC_EDIT_PWD_READ               1027
#define IDC_EDIT_WORDS_READ_USR         1027
#define IDC_EDIT_PORT                   1028
#define IDC_COMBO_IVNT_BUFTM            1028
#define IDC_EDIT_WORDS_WRITE_USR        1028
#define IDC_EDIT_IP                     1029
#define IDC_COMBO_INVT_QMINTRIES        1029
#define IDC_BTN_INVENTORY               1031
#define IDC_BTN_CLEAR                   1032
#define IDC_CHECK_READ_ANY              1032
#define IDC_EDIT_PASSWORD               1033
#define IDC_CHECK_WRITE_ANY             1033
#define IDC_EDIT_CUSTOMNO               1034
#define IDC_CHECK_READ_CONTINUE         1034
#define IDC_GRP_TCPIP                   1035
#define IDC_CHECK_WRITE_CONTINUE        1035
#define IDC_STATIC_IP                   1036
#define IDC_STATIC_PORT                 1037
#define IDC_STATIC_COMPORT              1038
#define IDC_STATIC_NODEADDR             1039
#define IDC_GRP_COM                     1040
#define IDC_EDIT_VERSION                1041
#define IDC_EDIT_MODEL                  1042
#define IDC_EDIT_DEVSN                  1043
#define IDC_EDIT_NETADDR                1044
#define IDC_TAB_NETADDR                 1046
#define IDC_BTN_NODE_EXPLORE            1047
#define IDC_TAB_PANES                   1048
#define IDC_BTN_NODE_SET                1048
#define IDC_LIST_NODES                  1049
#define IDC_EDIT_NETIP                  1050
#define IDC_EDIT_READER_IP              1051
#define IDC_EDIT_GATEWAY                1051
#define IDC_EDIT_READER_MASK            1052
#define IDC_EDIT_READER_GATEWAY         1053
#define IDC_EDIT_NETMASK                1053
#define IDC_COMBO_IVNT_RSPTM            1056
#define IDC_EDIT_EMSG                   1057
#define IDC_BTN_TAG_READ_TID            1058
#define IDC_EDIT_DATA_READ_TID          1059
#define IDC_BTN_TAG_READ_USR            1060
#define IDC_EDIT_DATA_READ_USR          1061
#define IDC_EDIT_WORDS_READ_TID         1062
#define IDC_EDIT_START_READ_TID         1063
#define IDC_BTN_TAG_WRITE_USR           1064
#define IDC_BTN_TAG_WRITE_EPC           1065
#define IDC_BTN_TAG_WRITE_PWD           1066
#define IDC_EDIT_DATA_WRITE_USR         1067
#define IDC_BTN_TAG_LOCK_USR            1068
#define IDC_BTN_TAG_LOCK_EPC            1069
#define IDC_BTN_TAG_KILL_EX             1070
#define IDC_EDIT_KILL_PWD               1071
#define IDC_CHECK_ACCPWD                1072
#define IDC_CHECK_KILPWD                1073
#define IDC_RADIO_COM                   1074
#define IDC_RADIO_RS485                 1075
#define IDC_RADIO_CAN                   1076
#define IDC_RADIO_UDP                   1077
#define IDC_RADIO_TCP                   1078
#define IDC_CHECK_NOCRC                 1079
#define IDC_EDIT_NODE_SN                1085

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
